---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: "${CLUSTER_NAME}"

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KindCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  workerMachineCount: ${WORKER_MACHINE_COUNT}
  controlPlaneMachineCount: ${CONTROL_PLANE_MACHINE_COUNT}
  kubernetesVersion: "${KUBERNETES_VERSION}"
